[package]
name = "near2aurora"
version = "0.1.0"
authors = ["danielwpz"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = """
Helper module to call aurora smart contracts from NEAR.
"""

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "4.1.1"
ethabi = "17.2.0"
hex = "0.4"
primitive-types = "0.12.1"
getrandom = { version = "0.2", features = ["custom"] }
