[package]
name = "near2aurora"
version = "0.1.0"
authors = ["danielwpz"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/danielwpz/near2aurora"
repository = "https://github.com/danielwpz/near2aurora"
description = """
Helper module to call aurora smart contracts from NEAR.
"""

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "4.1.1"
ethabi = "17.2.0"
hex = "0.4"
getrandom = { version = "0.2", features = ["custom"] }
aurora-engine-types = { git = "https://github.com/aurora-is-near/aurora-engine.git", rev = "f6747cbe1176c298e9d6fb5dab59f73cc1081e21", default-features = false, features = ["contracts-std", "impl-serde"] }
aurora-engine-sdk = { git = "https://github.com/aurora-is-near/aurora-engine.git", rev = "f6747cbe1176c298e9d6fb5dab59f73cc1081e21", default-features = false, features = ["contract"] }
